# Generated by Django 5.2.1 on 2025-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='offer_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdata',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
