# Generated by Django 5.2.1 on 2025-05-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_productdata_offer_price_productdata_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='category',
            new_name='category_name',
        ),
    ]
