# Generated by Django 5.2.1 on 2025-07-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_rename_category_productdata_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Gender',
            new_name='Category_Product',
        ),
    ]
