# Generated by Django 5.2.1 on 2025-07-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0004_rename_category_gender_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='size',
        ),
    ]
