# Generated by Django 5.2.1 on 2025-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPasswordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('otp_expiration', models.DateTimeField(blank=True, null=True)),
                ('otp_varified', models.BooleanField(default=False)),
            ],
        ),
    ]
