# Generated by Django 5.2.1 on 2025-05-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_forgetpassworduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgetPasswordUser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_varified',
            field=models.BooleanField(default=False),
        ),
    ]
