# Generated by Django 5.2.1 on 2025-07-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlistuser_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofuser', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('houseno_buildingname', models.CharField(max_length=100)),
                ('Roadname', models.CharField(max_length=100)),
            ],
        ),
    ]
