# Generated by Django 5.2.1 on 2025-07-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_useraddress_adduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useraddress',
        ),
    ]
