# Generated by Django 5.2.1 on 2025-07-22 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Useraddressuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Useraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofuser', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('houseno_buildingname', models.CharField(max_length=100)),
                ('Roadname', models.CharField(max_length=100)),
                ('adduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.useraddressuser')),
            ],
        ),
    ]
