# Generated by Django 5.2.1 on 2025-07-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_useraddressuser_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='adduser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.useraddressuser'),
        ),
    ]
