# Generated by Django 5.2.1 on 2025-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_useraddressuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
